volumes:
  nextcloud:
  db:
  redis_data:  

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    hostname: ncdb 
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - ncnetwork

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: ncsrv
    restart: unless-stopped
    ports:
      - "8020:80"
    depends_on:
      - db
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - nextcloud:/var/www/html
    networks:
      - ncnetwork

  collabora:
    image: collabora/code
    container_name: collabora
    hostname: collabora
    restart: unless-stopped
    environment:
      - domain=ncsrv
      - username=admin
      - password=${COLLABORA_PASSWORD}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    ports:
      - "9980:9980"
    networks:
      - ncnetwork

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    hostname: nextcloud_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - ncnetwork       
networks:
  ncnetwork:
    driver: bridge
